#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.TRecursive import fix_spec

all_structs = []


class YFileType(object):
    YBDF = 0
    YTDF = 1

    _VALUES_TO_NAMES = {
        0: "YBDF",
        1: "YTDF",
    }

    _NAMES_TO_VALUES = {
        "YBDF": 0,
        "YTDF": 1,
    }


class EyeStatus(object):
    NONE = 0
    OPEN = 1
    CLOSE = 2

    _VALUES_TO_NAMES = {
        0: "NONE",
        1: "OPEN",
        2: "CLOSE",
    }

    _NAMES_TO_VALUES = {
        "NONE": 0,
        "OPEN": 1,
        "CLOSE": 2,
    }


class DimensionType(object):
    NONE = 0
    RAW = 1
    nV = 2
    uV = 3
    mV = 4
    V = 5
    DIG_2 = 6
    DIG_3 = 7
    INT_4 = 8

    _VALUES_TO_NAMES = {
        0: "NONE",
        1: "RAW",
        2: "nV",
        3: "uV",
        4: "mV",
        5: "V",
        6: "DIG_2",
        7: "DIG_3",
        8: "INT_4",
    }

    _NAMES_TO_VALUES = {
        "NONE": 0,
        "RAW": 1,
        "nV": 2,
        "uV": 3,
        "mV": 4,
        "V": 5,
        "DIG_2": 6,
        "DIG_3": 7,
        "INT_4": 8,
    }


class TransducerType(object):
    NONE = 0
    DRY = 1
    WET = 2

    _VALUES_TO_NAMES = {
        0: "NONE",
        1: "DRY",
        2: "WET",
    }

    _NAMES_TO_VALUES = {
        "NONE": 0,
        "DRY": 1,
        "WET": 2,
    }


class MontageType(object):
    NONE = 0
    A1_REF = 1
    LONG_BI = 2
    TRANS_BI = 3
    CZ_REF = 4
    LINKED_EARS = 5
    LINKED_MASTOIDS = 6

    _VALUES_TO_NAMES = {
        0: "NONE",
        1: "A1_REF",
        2: "LONG_BI",
        3: "TRANS_BI",
        4: "CZ_REF",
        5: "LINKED_EARS",
        6: "LINKED_MASTOIDS",
    }

    _NAMES_TO_VALUES = {
        "NONE": 0,
        "A1_REF": 1,
        "LONG_BI": 2,
        "TRANS_BI": 3,
        "CZ_REF": 4,
        "LINKED_EARS": 5,
        "LINKED_MASTOIDS": 6,
    }


class SignalGroup(object):
    UNKNOWN = 0
    EEG_INDEX = 1
    EEG_DATA = 2
    GYRO_INDEX = 3
    GYRO_DATA = 4
    ACCEL_INDEX = 5
    ACCEL_DATA = 6
    MAGNETIC_INDEX = 7
    MAGNETIC_DATA = 8
    ANNOTATION = 100
    SQI = 101

    _VALUES_TO_NAMES = {
        0: "UNKNOWN",
        1: "EEG_INDEX",
        2: "EEG_DATA",
        3: "GYRO_INDEX",
        4: "GYRO_DATA",
        5: "ACCEL_INDEX",
        6: "ACCEL_DATA",
        7: "MAGNETIC_INDEX",
        8: "MAGNETIC_DATA",
        100: "ANNOTATION",
        101: "SQI",
    }

    _NAMES_TO_VALUES = {
        "UNKNOWN": 0,
        "EEG_INDEX": 1,
        "EEG_DATA": 2,
        "GYRO_INDEX": 3,
        "GYRO_DATA": 4,
        "ACCEL_INDEX": 5,
        "ACCEL_DATA": 6,
        "MAGNETIC_INDEX": 7,
        "MAGNETIC_DATA": 8,
        "ANNOTATION": 100,
        "SQI": 101,
    }


class SignalLabel(object):
    NONE = 0
    EEG_INDEX = 1
    Nz = 2
    Iz = 3
    A1 = 4
    A2 = 5
    FP1 = 6
    FP2 = 7
    FPz = 8
    AF3 = 9
    AF4 = 10
    AF7 = 11
    AF8 = 12
    AFz = 13
    F1 = 14
    F2 = 15
    F3 = 16
    F4 = 17
    F5 = 18
    F6 = 19
    F7 = 20
    F8 = 21
    F9 = 22
    F10 = 23
    Fz = 24
    FC1 = 25
    FC2 = 26
    FC3 = 27
    FC4 = 28
    FC5 = 29
    FC6 = 30
    FCz = 31
    FT7 = 32
    FT8 = 33
    FT9 = 34
    FT10 = 35
    T3 = 36
    T4 = 37
    T9 = 38
    T10 = 39
    C1 = 40
    C2 = 41
    C3 = 42
    C4 = 43
    C5 = 44
    C6 = 45
    Cz = 46
    TP7 = 47
    TP8 = 48
    TP9 = 49
    TP10 = 50
    CP1 = 51
    CP2 = 52
    CP3 = 53
    CP4 = 54
    CP5 = 55
    CP6 = 56
    CPz = 57
    P1 = 58
    P2 = 59
    P3 = 60
    P4 = 61
    P5 = 62
    P6 = 63
    T5 = 64
    P9 = 65
    T6 = 66
    P10 = 67
    Pz = 68
    PO3 = 69
    PO4 = 70
    PO7 = 71
    PO8 = 72
    POz = 73
    O1 = 74
    O2 = 75
    Oz = 76
    EEG_SQI = 77
    GYRO_INDEX = 100
    GYRO_X = 101
    GYRO_Y = 102
    GYRO_Z = 103
    ACCEL_INDEX = 104
    ACCEL_X = 105
    ACCEL_Y = 106
    ACCEL_Z = 107
    MAGNETIC_INDEX = 108
    MAGNETIC_X = 109
    MAGNETIC_Y = 110
    MAGNETIC_Z = 111
    ANNOTATION = 1000

    _VALUES_TO_NAMES = {
        0: "NONE",
        1: "EEG_INDEX",
        2: "Nz",
        3: "Iz",
        4: "A1",
        5: "A2",
        6: "FP1",
        7: "FP2",
        8: "FPz",
        9: "AF3",
        10: "AF4",
        11: "AF7",
        12: "AF8",
        13: "AFz",
        14: "F1",
        15: "F2",
        16: "F3",
        17: "F4",
        18: "F5",
        19: "F6",
        20: "F7",
        21: "F8",
        22: "F9",
        23: "F10",
        24: "Fz",
        25: "FC1",
        26: "FC2",
        27: "FC3",
        28: "FC4",
        29: "FC5",
        30: "FC6",
        31: "FCz",
        32: "FT7",
        33: "FT8",
        34: "FT9",
        35: "FT10",
        36: "T3",
        37: "T4",
        38: "T9",
        39: "T10",
        40: "C1",
        41: "C2",
        42: "C3",
        43: "C4",
        44: "C5",
        45: "C6",
        46: "Cz",
        47: "TP7",
        48: "TP8",
        49: "TP9",
        50: "TP10",
        51: "CP1",
        52: "CP2",
        53: "CP3",
        54: "CP4",
        55: "CP5",
        56: "CP6",
        57: "CPz",
        58: "P1",
        59: "P2",
        60: "P3",
        61: "P4",
        62: "P5",
        63: "P6",
        64: "T5",
        65: "P9",
        66: "T6",
        67: "P10",
        68: "Pz",
        69: "PO3",
        70: "PO4",
        71: "PO7",
        72: "PO8",
        73: "POz",
        74: "O1",
        75: "O2",
        76: "Oz",
        77: "EEG_SQI",
        100: "GYRO_INDEX",
        101: "GYRO_X",
        102: "GYRO_Y",
        103: "GYRO_Z",
        104: "ACCEL_INDEX",
        105: "ACCEL_X",
        106: "ACCEL_Y",
        107: "ACCEL_Z",
        108: "MAGNETIC_INDEX",
        109: "MAGNETIC_X",
        110: "MAGNETIC_Y",
        111: "MAGNETIC_Z",
        1000: "ANNOTATION",
    }

    _NAMES_TO_VALUES = {
        "NONE": 0,
        "EEG_INDEX": 1,
        "Nz": 2,
        "Iz": 3,
        "A1": 4,
        "A2": 5,
        "FP1": 6,
        "FP2": 7,
        "FPz": 8,
        "AF3": 9,
        "AF4": 10,
        "AF7": 11,
        "AF8": 12,
        "AFz": 13,
        "F1": 14,
        "F2": 15,
        "F3": 16,
        "F4": 17,
        "F5": 18,
        "F6": 19,
        "F7": 20,
        "F8": 21,
        "F9": 22,
        "F10": 23,
        "Fz": 24,
        "FC1": 25,
        "FC2": 26,
        "FC3": 27,
        "FC4": 28,
        "FC5": 29,
        "FC6": 30,
        "FCz": 31,
        "FT7": 32,
        "FT8": 33,
        "FT9": 34,
        "FT10": 35,
        "T3": 36,
        "T4": 37,
        "T9": 38,
        "T10": 39,
        "C1": 40,
        "C2": 41,
        "C3": 42,
        "C4": 43,
        "C5": 44,
        "C6": 45,
        "Cz": 46,
        "TP7": 47,
        "TP8": 48,
        "TP9": 49,
        "TP10": 50,
        "CP1": 51,
        "CP2": 52,
        "CP3": 53,
        "CP4": 54,
        "CP5": 55,
        "CP6": 56,
        "CPz": 57,
        "P1": 58,
        "P2": 59,
        "P3": 60,
        "P4": 61,
        "P5": 62,
        "P6": 63,
        "T5": 64,
        "P9": 65,
        "T6": 66,
        "P10": 67,
        "Pz": 68,
        "PO3": 69,
        "PO4": 70,
        "PO7": 71,
        "PO8": 72,
        "POz": 73,
        "O1": 74,
        "O2": 75,
        "Oz": 76,
        "EEG_SQI": 77,
        "GYRO_INDEX": 100,
        "GYRO_X": 101,
        "GYRO_Y": 102,
        "GYRO_Z": 103,
        "ACCEL_INDEX": 104,
        "ACCEL_X": 105,
        "ACCEL_Y": 106,
        "ACCEL_Z": 107,
        "MAGNETIC_INDEX": 108,
        "MAGNETIC_X": 109,
        "MAGNETIC_Y": 110,
        "MAGNETIC_Z": 111,
        "ANNOTATION": 1000,
    }
fix_spec(all_structs)
del all_structs
