TEST_INFO = {
    'subject': {'id': 253, 'orgzId': 156, 'remarks': None, 'created': '2020-08-13T01:07:37',
                'empMail': 'xogys12@gmail.com', 'code': 'test', 'name': '홍길동', 'birthday': 19900801,
                'sex': 'MALE', 'handedness': 'RIGHT', 'tel': '010-8889-6240', 'email': '', 'address': None,
                'manager': None, 'comment': '', 'indications': []},
    'anlzRequest': {'orgzId': 156, 'subjectId': 253, 'employeeEmail': 'xogys12@gmail.com', 'employeeName': '박우민',
                    'anlzSources': [], 'anlzAlgorithm': 'ICA',
                    'anlzStatus': 'PROCEEDING', 'anlzType': 'INDIVIDUAL', 'statusTime': '2020-08-14T05:43:09.566',
                    'visualResultFile': None, 'actualResultFile': None,
                    'resultFileSize': 0, 'hasSurvey': True, 'deleted': False, 'appendix': True, 'orgzName': None,
                    'timeZone': '+09:00', 'id': 792, 'remarks': None,
                    'created': None,
                    'surveys': [{'id': 179, 'surveySessionId': 1163, 'surveyName': '기본 정신건강검사', 'created': None,
                                 'sessionAnlzResult': {'sessionId': 1163,
                                                       'mainAnlzResult': {'pubSurveyId': 67,
                                                                          'anlzResult': None,
                                                                          'surveyName': '기본 정신건강검사',
                                                                          'surveyDesc': '우울(PHQ-9), 두통(HIT-6), 불안(GAD-7)을 검사하기 위한 기본 설문 입니다.',
                                                                          'anlzSpec': None},
                                                       'subAnlzResults': [{'pubSurveyId': 8,
                                                                           'anlzResult': {
                                                                               'score': 12.0,
                                                                               'level': 3,
                                                                               'status': '3',
                                                                               'comment': '현재 작성하신 설문지는 우울증상의 정도를 측정하는 설문지이며 점수는 (#) 점 이예요. 이 상태가 오랫동안 지속되기 시작하면 더 깊은 우울감에 빠질 수 있어요. 혼자서만 생각하지 마시고 자신의 마음을 돌아보는 시간을 충분히 가지세요. 혼자서 어렵다면 주변 사람이나 외부의 관심과 관리를 통해서 좀 더 신경쓸 필요가 있을 것 같아요.',
                                                                               'anlzedTime': '2020-08-14T05:33:20.717',
                                                                               'additions': None},
                                                                           'surveyName': 'PHQ-9',
                                                                           'surveyDesc': '자가 우울증 평가 도구(Patient Health Questionnaire-9)',
                                                                           'anlzSpec': {
                                                                               'type': 'SCORE',
                                                                               'comment': None,
                                                                               'scoreType': 'SUM',
                                                                               'rawScoreType': None,
                                                                               'maxScore': 27.0,
                                                                               'minScore': 0.0,
                                                                               'minLevel': 1,
                                                                               'maxLevel': 5,
                                                                               'ranges': [
                                                                                   {'level': 1,
                                                                                    'min': 0.0,
                                                                                    'max': 4.0,
                                                                                    'status': '1',
                                                                                    'comment': '현재 작성하신 설문지는 우울증상의 정도를 측정하는 설문지이며 점수는 (#) 점 이예요. 다행히도 지금은 마음이 건강해 보이세요. 주변 사람들과도 원활하게 잘 지내시는 것 같네요. 계속해서 지금처럼 마음이 건강할 수 있도록 유지하세요.'},
                                                                                   {'level': 2,
                                                                                    'min': 5.0,
                                                                                    'max': 9.0,
                                                                                    'status': '2',
                                                                                    'comment': '현재 작성하신 설문지는 우울증상의 정도를 측정하는 설문지이며 점수는 (#) 점 이예요. 마음이 항상 즐거운 건 아니지만, 종종 기분이 좋지 않고 가벼운 우울감을 느끼시는 것 같아요. 같은 일상에서 벗어나 다른 환경에서 기분전환을 시도해보는 건 어떠세요? 사람들도 만나보고 좀 더 활동적으로 일상을 바꿔보는 것도 좋을 것 같아요.'},
                                                                                   {'level': 3,
                                                                                    'min': 10.0,
                                                                                    'max': 14.0,
                                                                                    'status': '3',
                                                                                    'comment': '현재 작성하신 설문지는 우울증상의 정도를 측정하는 설문지이며 점수는 (#) 점 이예요. 이 상태가 오랫동안 지속되기 시작하면 더 깊은 우울감에 빠질 수 있어요. 혼자서만 생각하지 마시고 자신의 마음을 돌아보는 시간을 충분히 가지세요. 혼자서 어렵다면 주변 사람이나 외부의 관심과 관리를 통해서 좀 더 신경쓸 필요가 있을 것 같아요.'},
                                                                                   {'level': 4,
                                                                                    'min': 15.0,
                                                                                    'max': 19.0,
                                                                                    'status': '4',
                                                                                    'comment': '현재 작성하신 설문지는 우울증상의 정도를 측정하는 설문지이며 점수는 (#) 점 이예요. 마음도 항상 무겁고, 스트레스가 많으셔서 주변 사람들과 원활하게 지내기 어려웠나요? 다른 사람들은 모르는 곳에서 혼자서 끙끙 앓지 마시고 용기를 내서 주변사람들의 도움을 받으시는 게 좋아요. 우선은 전문가의 도움이 필요하다고 보여요.'},
                                                                                   {'level': 5,
                                                                                    'min': 20.0,
                                                                                    'max': 27.0,
                                                                                    'status': '5',
                                                                                    'comment': '현재 작성하신 설문지는 우울증상의 정도를 측정하는 설문지이며 점수는 (#) 점 이예요. 일상이 늘 지치고 힘들어서 하루하루 견뎌내기가 힘드실 것 같아요. 점점 더 힘들어지기 전에 전문가를 찾아서 도움을 구하고, 차근차근 상담과 치료를 받으신다면 혼자 안고 있는 것 보다 훨씬 관리하기 수월하실거에요. 괜찮아요. 혼자 힘들어하지 마시고 도움을 구해보세요.'}],
                                                                               'additionOperations': None,
                                                                               'scoredByTagging': None,
                                                                               'lowGood': True,
                                                                               'zscoreM': None,
                                                                               'zscoreS': None}},
                                                                          {'pubSurveyId': 9,
                                                                           'anlzResult': {
                                                                               'score': 54.0,
                                                                               'level': 2,
                                                                               'status': '2',
                                                                               'comment': '현재 작성하신 설문지는 두통의 영향을 측정하는 설문지이며 점수는 (#) 점 이예요. 현재 당신의 삶에 두통이 약간의 영향을 주고 있는 것 같아요. 이러한 두통은 가족과 일 또는 학교, 그밖의 어떠한 사회적 활동을 진행하는 데에 영향을 줄 수 있어요. 편안한 휴식과 숙면은 가벼운 두통을 호전시키는데에 도움을 되요. 계속 두통이 지속된다면 전문가와 약속을 잡고 상담을 받아보시는 것도 권해드려요.',
                                                                               'anlzedTime': '2020-08-14T05:33:20.725',
                                                                               'additions': None},
                                                                           'surveyName': 'HIT-6',
                                                                           'surveyDesc': '두통 영향 평가(Headache Impact Test-6)',
                                                                           'anlzSpec': {
                                                                               'type': 'SCORE',
                                                                               'comment': None,
                                                                               'scoreType': 'SUM',
                                                                               'rawScoreType': None,
                                                                               'maxScore': 78.0,
                                                                               'minScore': 36.0,
                                                                               'minLevel': 1,
                                                                               'maxLevel': 4,
                                                                               'ranges': [
                                                                                   {'level': 1,
                                                                                    'min': 36.0,
                                                                                    'max': 49.0,
                                                                                    'status': '1',
                                                                                    'comment': '현재 작성하신 설문지는 두통의 영향을 측정하는 설문지이며 점수는 (#) 점 이예요. 다행히도 당신의 삶에 두통이 어떤 큰 영향을 주고 있진 않아요. 한달에 한 번 정도는 두통 설문지를 통해 주기적으로 관찰하시는 것도 현재 상태를 유지하기 위한 좋은 방법이예요.'},
                                                                                   {'level': 2,
                                                                                    'min': 50.0,
                                                                                    'max': 55.0,
                                                                                    'status': '2',
                                                                                    'comment': '현재 작성하신 설문지는 두통의 영향을 측정하는 설문지이며 점수는 (#) 점 이예요. 현재 당신의 삶에 두통이 약간의 영향을 주고 있는 것 같아요. 이러한 두통은 가족과 일 또는 학교, 그밖의 어떠한 사회적 활동을 진행하는 데에 영향을 줄 수 있어요. 편안한 휴식과 숙면은 가벼운 두통을 호전시키는데에 도움을 되요. 계속 두통이 지속된다면 전문가와 약속을 잡고 상담을 받아보시는 것도 권해드려요.'},
                                                                                   {'level': 3,
                                                                                    'min': 56.0,
                                                                                    'max': 59.0,
                                                                                    'status': '3',
                                                                                    'comment': '현재 작성하신 설문지는 두통의 영향을 측정하는 설문지이며 점수는 (#) 점 이예요. 현재 당신의 삶에 두통이 상당한 영향을 주고 있는 것 같아요. 휴식으로도 해결되지 않는 두통은 당신의 몸에 다른 증상과 심각한 고통 등을 동반하게 될 수 있어요. 오늘 평가 받은 설문지 결과와 함께 빠른 시일내에 전문가의 상담을 받고 치료 계획을 세우는 것을 권해드려요. 두통은 가족과 일 또는 학교, 그밖의 어떠한 사회적 활동을 진행하는 데에 많은 영향을 줄 수 있어요.'},
                                                                                   {'level': 4,
                                                                                    'min': 60.0,
                                                                                    'max': 78.0,
                                                                                    'status': '4',
                                                                                    'comment': '현재 작성하신 설문지는 두통의 영향을 측정하는 설문지이며 점수는 (#) 점 이예요. 현재 당신의 삶에 두통이 심각한 영향을 주고 있는 것 같아요. 많이 힘드셨겠어요. 이러한 두통은 당신의 몸에 다른 증상과 심각한 고통 등을 동반하게 될 수 있어요. 오늘 평가 받은 설문지 결과와 함께 오늘이라도 전문가의 상담을 받고 치료를 진행하시는 것을 권해드려요. 심각한 두통은 가족과 일 또는 학교, 그밖의 어떠한 사회적 활동을 진행하는 데에 많은 영향을 줄 수 있어요.'}],
                                                                               'additionOperations': None,
                                                                               'scoredByTagging': None,
                                                                               'lowGood': True,
                                                                               'zscoreM': None,
                                                                               'zscoreS': None}},
                                                                          {'pubSurveyId': 10,
                                                                           'anlzResult': {
                                                                               'score': 12.0,
                                                                               'level': 3,
                                                                               'status': '3',
                                                                               'comment': '현재 작성하신 설문지는 불안증상의 정도를 측정하는 설문지이며 점수는 (#) 점 이예요. 현재 중증의 불안 증세를 보이는 것 같아요. 불안 증세를 치료하기 위해서는 불안의 원인을 해결하는 것이 가장 중요해요. 그렇기 때문에 다양한 불안장애 중에서 어느 불안장애 인지 빠른 진단이 필요해보여요. 오늘 평가받은 설문지 결과와 함께 빠른 시일내에 전문가와 상담을 통하여 정확한 불안장애의 진단이 필요해요. 불안장애는 방치하지 말고 치료를 잘 받으면 비교적 수월하게 호전될 수 있어요.',
                                                                               'anlzedTime': '2020-08-14T05:33:20.732',
                                                                               'additions': None},
                                                                           'surveyName': 'GAD-7',
                                                                           'surveyDesc': '범불안장애 자가 설문 도구',
                                                                           'anlzSpec': {
                                                                               'type': 'SCORE',
                                                                               'comment': None,
                                                                               'scoreType': 'SUM',
                                                                               'rawScoreType': None,
                                                                               'maxScore': 21.0,
                                                                               'minScore': 0.0,
                                                                               'minLevel': 1,
                                                                               'maxLevel': 4,
                                                                               'ranges': [
                                                                                   {'level': 1,
                                                                                    'min': 0.0,
                                                                                    'max': 4.0,
                                                                                    'status': '1',
                                                                                    'comment': '현재 작성하신 설문지는 불안증상의 정도를 측정하는 설문지이며 점수는 (#) 점 이예요. 다행히도 지금은 불안한 증세는 거의 없고 건강한 마음을 가지고 있으세요. 계속해서 지금처럼 마음이 건강할 수 있도록 유지하세요. 한달에 한 번 정도는 설문지를 통해 주기적으로 관찰하시는 것도 현재 상태를 유지하기 위한 좋은 방법이예요.'},
                                                                                   {'level': 2,
                                                                                    'min': 5.0,
                                                                                    'max': 9.0,
                                                                                    'status': '2',
                                                                                    'comment': '현재 작성하신 설문지는 불안증상의 정도를 측정하는 설문지이며 점수는 (#) 점 이예요. 현재 약간의 불안 증세를 보이는 것 같아요. 불안은 위협이나 신체적 스트레스에 대한 정상적인 반응이며, 모든 사람이 가끔 경험하는 증상이니 너무 걱정하지 마세요. 약간의 불안 증세는 생활 습관의 변화나 이완 훈련, 운동과 휴식 등을 통하여 불안을 조절하려고 먼저 노력해보는 것이 필요해요. 그래도 불안 증세가 조절이 안된다면 전문가의 상담이 필요해요.'},
                                                                                   {'level': 3,
                                                                                    'min': 10.0,
                                                                                    'max': 14.0,
                                                                                    'status': '3',
                                                                                    'comment': '현재 작성하신 설문지는 불안증상의 정도를 측정하는 설문지이며 점수는 (#) 점 이예요. 현재 중증의 불안 증세를 보이는 것 같아요. 불안 증세를 치료하기 위해서는 불안의 원인을 해결하는 것이 가장 중요해요. 그렇기 때문에 다양한 불안장애 중에서 어느 불안장애 인지 빠른 진단이 필요해보여요. 오늘 평가받은 설문지 결과와 함께 빠른 시일내에 전문가와 상담을 통하여 정확한 불안장애의 진단이 필요해요. 불안장애는 방치하지 말고 치료를 잘 받으면 비교적 수월하게 호전될 수 있어요.'},
                                                                                   {'level': 4,
                                                                                    'min': 15.0,
                                                                                    'max': 21.0,
                                                                                    'status': '4',
                                                                                    'comment': '현재 작성하신 설문지는 불안증상의 정도를 측정하는 설문지이며 점수는 (#) 점 이예요. 현재 심각한 불안 증세를 보이는 것 같아요. 많이 힘드셨겠어요. 불안 증세를 치료하기 위해서는 불안의 원인을 해결하는 것이 가장 중요해요. 그렇기 때문에 다양한 불안장애 중에서 어느 불안장애 인지 빠른 진단이 필요해보여요. 오늘 평가받은 설문지 결과와 함께 빠른 시일내에 전문가와 상담을 통하여 정확한 불안장애의 진단이 필요해요. 불안장애는 방치하지 말고 치료를 잘 받으면 비교적 수월하게 호전될 수 있어요. 전문가와 상담 시에는 현재 스트레스 상태, 신체적 상태, 가족력, 복용약물 등에 대한 자세한 내용을 꼭 함께 전달해주세요.'}],
                                                                               'additionOperations': None,
                                                                               'scoredByTagging': None,
                                                                               'lowGood': True,
                                                                               'zscoreM': None,
                                                                               'zscoreS': None}}]}}]},
    'spec': None}
